const evidence = "Use verified data available to you, cite source links and as-of dates, distinguish observations from interpretation, and explicitly identify unavailable data. Do not invent current figures or claim to operate a tool you cannot access.";
const suggestion = (title, description, path, task) => ({ title, description, path, prompt: `${task}\n\nRelated Luna Terminal tool: ${path}\n\n${evidence}` });

export const CHAT_SUGGESTIONS = [
  suggestion("Read the market", "What is market sentiment today?", "/dashboard", "Retrieve the latest market sentiment score on its 0–100 scale. Explain its rating, timestamp, and change from the previous available reading. Separate sentiment from price direction and describe which supporting indicators would confirm or challenge the reading."),
  suggestion("Research a stock", "Compare NVDA and SPY over the last year.", "/portfolio-comparison", "Compare NVDA and SPY over the latest available one-year period using matching start and end dates. Show starting and ending prices, percentage changes, and relative performance. State whether prices are adjusted and whether dividends are included. Link to each stock chart and the portfolio comparison tool."),
  suggestion("Find a Luna tool", "Where can I review Berkshire Hathaway’s holdings?", "/13Filings", "Guide me to Berkshire Hathaway's 13F holdings in Luna Terminal. Explain how to locate the latest filing, identify its reporting quarter, compare positions with the previous quarter, and distinguish reported share changes from changes in market value. Explain the filing delay and that 13F holdings do not represent the entire portfolio."),
  suggestion("Apple research brief", "Price, business, trend, and risks for AAPL.", "/stock/AAPL", "Prepare a structured AAPL research brief: latest available quote and timestamp, business overview, one-year price change, and key business risks. Distinguish technical observations from fundamental conclusions. Link to the AAPL stock page and identify additional data needed before reaching a valuation conclusion."),
  suggestion("Microsoft versus Alphabet", "Compare MSFT and GOOGL on matching dates.", "/portfolio-comparison", "Compare MSFT and GOOGL over the latest available one-year period. Use identical dates, show percentage price changes and benchmark each against SPY. Describe their principal business exposures, separate verified financial metrics from qualitative analysis, and disclose dividend and adjustment limitations."),
  suggestion("Semiconductor check", "Compare NVDA, AMD, and SOXX performance.", "/stock/NVDA", "Retrieve NVDA, AMD, and SOXX quotes and one-year histories. Compare returns on matching dates, describe SOXX as a semiconductor ETF rather than an individual company, and discuss concentration and industry-cycle risks. Link to each ticker's chart and explain any missing data."),
  suggestion("Broad market comparison", "SPY, QQQ, and IWM over the same year.", "/portfolio-comparison", "Compare SPY, QQQ, and IWM over the latest available year using the same dates. Explain the different market exposures, calculate comparable percentage price changes, and identify the strongest and weakest performers. State whether this is price return or total return and link to the comparison tool."),
  suggestion("Gold and stocks", "Compare GLD and SPY without assuming a hedge.", "/stock/GLD", "Compare GLD and SPY over the latest available year. Explain GLD's gold exposure, report matching-date price performance, and discuss why historical diversification does not guarantee protection. Only report correlation if enough aligned observations are available and explain the calculation."),
  suggestion("Bitcoin versus Ethereum", "BTC-USD and ETH-USD with dated sources.", "/global-markets", "Retrieve BTC-USD and ETH-USD quotes and one-year histories. Compare price changes on matching dates, identify quote currencies and timestamps, explain the difference between price performance and yield, and describe volatility and liquidity risks. Link to the global markets tool and source data."),
  suggestion("Global market snapshot", "World indexes, commodities, and volatility.", "/global-markets", "Guide me through a global market snapshot using Luna's global markets page. Group available indexes, commodities, and volatility measures by asset class. Report timestamps and trading-session differences, distinguish index levels from investable ETF prices, and avoid treating stale or closed-market quotes as simultaneous live readings."),
  suggestion("Sentiment versus SPY", "Check whether price and sentiment agree.", "/dashboard", "Retrieve current market sentiment and SPY history, then compare sentiment changes with SPY price direction over matching available periods. Explain agreement or divergence without claiming causation. Link to the dashboard's sentiment comparison chart and state whether aligned historical sentiment data is available."),
  suggestion("Volatility context", "Explain VIX alongside market sentiment.", "/global-markets", "Retrieve the latest available ^VIX quote, SPY quote, and market sentiment reading. Explain VIX as an implied-volatility index, not a forecast of stock-market direction. Compare timestamps, describe what can and cannot be inferred from their combination, and link to the global markets page."),
  suggestion("Screen for companies", "Build a measurable screening checklist.", "/screener", "Help me build a stock-screening checklist using the filters actually available in Luna's stock screener. Explain market cap, valuation, performance, and technical criteria with units and missing-data handling. Separate illustrative thresholds from recommendations and provide the screener link; do not claim to have run unsupported filters."),
  suggestion("Read the stock map", "Interpret size, color, and concentration.", "/maps", "Explain how to use Luna's stock maps to investigate market performance and concentration. Verify the selected size metric and color metric before interpreting them. Describe what large tiles, clusters, and outliers mean, explain the limits of a single snapshot, and link to the maps tool."),
  suggestion("Largest companies", "Understand market-cap rankings and dates.", "/market-cap", "Guide me through Luna's companies-by-market-cap ranking. Explain market capitalization, its difference from enterprise value, and how share count and price affect it. Report ranking dates and currencies if data can be retrieved, and otherwise provide the tool link and a checklist without inventing rankings."),
  suggestion("Earnings preparation", "Dates, expectations, and implied moves.", "/earnings-calendar", "Help me prepare for upcoming earnings using Luna's earnings calendar. Identify reporting dates and session timing only when verified. Explain consensus estimates and option-implied moves, distinguish expectations from realized outcomes, and link to the calendar. Flag estimates, rescheduled dates, and unavailable options data."),
  suggestion("Read a 13F filing", "Holdings, share changes, and filing limits.", "/13Filings", "Explain how to review a fund's 13F filing in Luna. Cover reporting period, filing date, position value, shares, portfolio weight, and quarter-over-quarter changes. Distinguish a new reported position from a precisely dated purchase, describe disclosure limitations, and link to the hedge-fund tool."),
  suggestion("Supply-chain research", "Trace suppliers and customers with evidence.", "/supply-chain", "Show me how to investigate a company's suppliers and customers using Luna's supply-chain diagram. Explain upstream versus downstream relationships, ask for company selection if needed, cite evidence for specific connections, and distinguish documented relationships from inferred dependencies. Do not invent revenue exposure percentages."),
  suggestion("Compare fundamental metrics", "Explore relationships in a scatter plot.", "/chart-metrics", "Guide me through selecting two available fundamental metrics in Luna's chart-metrics tool. Explain units, comparable company selection, outliers, missing observations, and why a visible relationship is not causation. Provide the tool link and a reproducible analysis plan without claiming unperformed calculations."),
  suggestion("Regression checklist", "Alignment, fit, residuals, and uncertainty.", "/regression-analysis", "Explain how to evaluate a regression using Luna's regression-analysis tool. Specify matching dates, dependent and independent variables, sample size, coefficient interpretation, R-squared, residual checks, and uncertainty. Warn about look-ahead bias and spurious relationships; report fitted values only if calculated from available data."),
  suggestion("Headquarters geography", "Explore where companies are based.", "/company-world-map", "Explain how to research corporate headquarters using Luna's company world map. Distinguish headquarters location from operating footprint, revenue geography, and incorporation jurisdiction. Cite dated sources for specific locations, identify incomplete coverage, and link to the map."),
  suggestion("Options and RSI context", "Interpret gamma levels and RSI carefully.", "/rsi-le", "Guide me through Luna's GEX and RSI workspace. Explain gamma exposure, strike concentration, RSI's 0–100 scale, and timestamps. Distinguish a positive-GEX reclaim signal from a true zero-gamma crossing; do not claim a gamma flip without the full gamma curve. Link to the workspace and note data limitations."),
  suggestion("Build a watchlist", "Create a focused ticker-monitoring routine.", "/watchlist", "Help me plan a watchlist using Luna's watchlist page. Ask about asset universe and time horizon, explain ticker and currency verification, and suggest a routine for reviewing price, sentiment, and earnings context. Link to the watchlist and describe sign-in requirements without claiming to save items for me."),
  suggestion("Plan useful alerts", "Define thresholds and verify notification rules.", "/alerts", "Explain how to plan market-sentiment or ticker threshold alerts in Luna. Define the monitored value, threshold, crossing direction, and review cadence, then verify which controls the alert page exposes. Link to the alerts tool, identify account requirements, and do not claim an alert has been created."),
  suggestion("Country ETF comparison", "Compare exposures, currencies, and returns.", "/country-etfs", "Guide me through comparing country ETFs in Luna. Explain underlying country exposure, listing currency versus currency risk, fees, concentration, and matching-date performance. Use only verified holdings and return data, state dividend treatment, and link to the country ETF tool."),
  suggestion("US sector review", "Compare sector exposure and performance.", "/us-sectors", "Help me review US sectors using Luna's sector page. Explain sector ETF exposures and concentration, compare available performance on identical dates, and separate price changes from earnings or valuation claims. Link to the sector tool and identify source timestamps and missing information."),
  suggestion("Currency research", "Read FX quotes and distinguish base currencies.", "/currencies", "Explain how to use Luna's major-currencies page. Define base and quote currency, interpret an exchange-rate move with a numeric example clearly labeled illustrative, and compare only compatible pairs and timestamps. Link to the tool and do not invent live exchange rates."),
  suggestion("Yield curve context", "Compare maturities, countries, and dates.", "/global-yields", "Guide me through Luna's global-yields page. Explain bond yield, maturity, basis points, curve slope, and why rising yields can coincide with falling bond prices. Compare countries only with matched maturity and as-of dates; link to the tool and label missing or delayed observations."),
  suggestion("Compare several charts", "Use consistent periods across tickers.", "/lots-of-charts", "Explain how to research multiple tickers with Luna's Lots of Charts page. Choose matching time ranges, distinguish normalized percentage performance from raw price levels, and flag differences in trading calendars and adjustment methods. Link to the chart workspace and ask for tickers if none are supplied."),
  suggestion("Portfolio allocation review", "Assess weights, benchmarks, and assumptions.", "/portfolio-comparison", "Help me compare a hypothetical portfolio with SPY using Luna's portfolio comparison tool. Ask for tickers, weights, date range, and rebalancing assumptions. Check that weights sum to 100%, distinguish price returns from total returns, and report fees, dividends, and missing-data assumptions before interpreting any result."),
  suggestion("Find advisor tools", "Locate client portfolios, models, and reports.", "/finance-crm", "Show me where Luna's advisor tools are: Finance CRM, Client Portfolios, Model Portfolios, and Reports. Link to /finance-crm, /client-portfolios, /model-portfolios, and /reports. Describe each page based on verified functionality, explain account restrictions, and never invent client records or claim to access private data."),
  suggestion("Amazon research brief", "AMZN price, performance, business, and risks.", "/stock/AMZN", "Prepare an AMZN research brief using its latest available quote and one-year history. Compare percentage price performance with SPY on matching dates, describe Amazon's retail and cloud businesses, separate verified metrics from interpretation, and link to the stock page. Identify data needed for deeper valuation analysis."),
  suggestion("Market research workflow", "Connect sentiment, charts, earnings, and filings.", "/dashboard", "Build a reproducible Luna Terminal research workflow: check market sentiment on /dashboard, inspect a selected ticker's /stock/{SYMBOL} page, review /earnings-calendar, and consult /13Filings for institutional disclosure context. Explain each step's purpose, required evidence, timestamps, and limitations; ask for a ticker rather than choosing a personalized investment."),
];

export function nextSuggestions(previous, random = Math.random) {
  const candidates = CHAT_SUGGESTIONS.map((_, index) => index).filter(index => !previous.includes(index));
  for (let index = candidates.length - 1; index > 0; index--) {
    const other = Math.floor(random() * (index + 1));
    [candidates[index], candidates[other]] = [candidates[other], candidates[index]];
  }
  return candidates.slice(0, 3);
}
