// Pings IndexNow (Bing, Yandex, Seznam, Naver) with every URL in the sitemap.
// Bing's index feeds a lot of AI search, and IndexNow gets same-day pickup
// instead of waiting on a crawl. Run after a deploy: `node scripts/indexnow.mjs`
//
// The key must also be served at https://<host>/<key>.txt containing exactly
// the key - that file lives in public/ and is what proves we own the domain.

// Generated by Bing Webmaster Tools rather than by us. Either is valid to
// IndexNow, but using Bing's own key is what its dashboard expects to see, so
// submissions show up against the site there.
const KEY = process.env.INDEXNOW_KEY || "07008d47b95c40e6bf3e3d1dd66e01e4";
const HOST = process.env.SITE_HOST || "lunaterminal.com";

const paths = [
  "/",
];

const res = await fetch("https://api.indexnow.org/IndexNow", {
  method: "POST",
  headers: { "Content-Type": "application/json; charset=utf-8" },
  body: JSON.stringify({
    host: HOST,
    key: KEY,
    keyLocation: `https://${HOST}/${KEY}.txt`,
    urlList: paths.map((p) => `https://${HOST}${p}`),
  }),
});

// The status code is the only diagnostic IndexNow gives back, and the codes
// mean very different things - 403 is a key-hosting problem, 422 is a
// host/key mismatch. Spelling them out beats looking them up each time.
const REASONS = {
  200: "URLs submitted successfully",
  202: "accepted, key validation pending",
  400: "bad request - invalid format",
  403: `key not valid - check https://${HOST}/${KEY}.txt is reachable and contains exactly the key`,
  422: "URLs do not belong to the host, or the key does not match",
  429: "too many requests - throttled as potential spam",
};

console.log(
  `IndexNow: ${res.status} ${res.statusText} for ${paths.length} URLs` +
    `\n  ${REASONS[res.status] ?? "unrecognised response"}`,
);
if (!res.ok) process.exitCode = 1;
